In [3]:
##  Array


In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
conda install numpy

Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - numpy


The following packages will be UPDATED:

  conda                                        4.8.3-py38_0 --> 4.9.2-py38haa95532_0


Preparing transaction: ...working... done
Verifying transaction: ...working... failed

Note: you may need to restart the kernel to use updated packages.



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3




In [3]:
import numpy as np

In [1]:
my_lst=[1,2,3,4,5]

In [4]:
arr=np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
print(arr)

[1 2 3 4 5]


In [7]:
arr.shape

(5,)

In [10]:
### Multinested Array

In [22]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [12]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr.shape

(3, 5)

In [16]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

## Indexing

In [19]:
## accessing the array element

arr=np.array([1,2,3,4,5,6,7,8,9])

In [20]:
arr[3]

4

In [23]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [24]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [29]:
arr[1:3,3:5]

array([[5, 6],
       [8, 9]])

In [30]:
arr[1:,2:4]

array([[4, 5],
       [6, 8]])

In [31]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [32]:
arr=np.arange(0,10)

In [35]:
arr=np.arange(0,10,step=2)

In [36]:
arr

array([0, 2, 4, 6, 8])

In [37]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [38]:
## copy function and broadcasting


In [39]:
arr[3:]=100

In [40]:
arr

array([  0,   2,   4, 100, 100])

In [48]:
val=2

arr[arr<20]

array([0, 2, 4])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [51]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])